config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'pages#index'

  resources :aliments, only: [:index, :show] do
    get :autocomplete_aliment_name, on: :collection

  end

  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'
  post '/' => 'pages#send_contact_email', as: :send_contact_email

end

app/models/aliment.rb
class Aliment < ActiveRecord::Base

  # scope :name_like, -> (name) { where("name ilike ?", name)}

  searchkick word_start: [:name, :food_group]#, word_end: [:name, :food_group]

  has_one :proximate, dependent: :destroy
  has_one :mineral, dependent: :destroy
  has_one :vitamin, dependent: :destroy
  has_one :lipid, dependent: :destroy
  has_one :amino_acid, dependent: :destroy
  has_one :other, dependent: :destroy

  # Ensures that, when trying to save aliment, validates belonged models too
  validates_associated :proximate, :mineral, :vitamin, :lipid, :amino_acid, :other
  validates :name, presence: true

  def recent?
    updated_at >= Time.now - 6.months
  end

  # Searchkick specification
  def search_data
    as_json only: [:name, :food_group]
  end

end

app/controllers/aliments_controller.rb
class AlimentsController < ApplicationController
  autocomplete :aliment, :name

  before_action :set_search_action
  before_action :set_page, only: :index

  def index
    if params[:inputed_name].present?
      @aliments = Aliment.search(
        params[:inputed_name],
        page: params[:page],
        per_page: 20,
        operator: 'or',
        fields: [
          { name: :word_start },
          { food_group: :word_start }
        ]
      )
    else
      @aliments = Aliment.search('*', page: params[:page], per_page: 20)
      @aliment = nil
    end
  end

  def show
    @aliment = Aliment.find params[:id]
  end

  private

  def aliment_params
    params.require(:aliment).permit(:name, :food_group)
  end

  def set_search_action
    redirect_to action: :index, inputed_name: params[:name] if params.include?(:name)
  end
end

app/views/aliments/_aliment.html.erb
<%= link_to aliment_path(aliment), :class => 'gems__gem' do %>
  <span class="gems__gem__info">
    <h2 class="gems__gem__name">
      <%= aliment.name %>
      <span class="gems__gem__version"><%= aliment.id %></span>
    </h2>
    <p class="gems__gem__desc t-text">blablabla blablablabalblablabl bla</p>
  </span>
  <p class="gems__gem__downloads__count">
    <%= aliment.proximate.blank? ? '-' : @aliment.proximate.energy.round(2) %>
    <span class="gems__gem__downloads__heading">
      <%= t('rubygems.index.calories') %>
    </span>
  </p>
<% end %>

app/views/aliments/_aside.html.erb
<div class="gem__aside l-col--r--pad">
  <h2 class="gem__ruby-version__heading t-list__heading">
    <%= t 'rubygems.aside.desired_quantity' %>:
    <div class="gem__code-wrap">
      <input type="text" class="gem__code" id="gemfile_text" value="<%#= @latest_version.to_bundler %>">
      <span class="gem__code__icon" id="js-gem__code--gemfile" data-clipboard-target="#gemfile_text">=</span>
      <span class="gem__code__tooltip--copy"><%= t('rubygems.aside.quantity_tooltip') %></span>
      <span class="gem__code__tooltip--copied"><%= t('.copied') %></span>
    </div>
  </h2>

  <h2 class="gem__ruby-version__heading t-list__heading">
    <%#= t '.measures' %>
    <!-- <div class="gem__code-wrap">
      <input type="text" class="gem__code" id="install_text" value="<%#= @latest_version.to_install %>" readonly="readonly">
      <span class="gem__code__icon" id="js-gem__code--install" data-clipboard-target="#install_text">=</span>
    </div> -->
  </h2>

  <h3 class="t-list__heading"><%#= t '.links.header' %></h3>
  <div class="t-list__items">
    <%#= link_to t('edit'), edit_rubygem_path(@rubygem), :class => "gem__link t-list__item", :id => "edit" if @rubygem.owned_by?(current_user) %>

    <%#= badge_link(@rubygem) %>
  </div>
</div>

app/views/aliments/_show.html.haml
%div.modal-dialog#aliment
  %div.modal-content
    %div.modal-header
      %button{ type: 'button', class: 'close', data: { dismiss: 'modal' }, aria: { hidden: 'true' } }
        &times;
      .panel-title
        %h2.md-headline
          = "#{@aliment.name}"

    %div.modal-body
      - if @aliment.proximate.present?
        %h4.md-subhead
          = "Protein: ---------- #{@aliment.proximate.protein} g"
        %h4.md-subhead
          = "Carbohydrate: - #{@aliment.proximate.carbohydrate} g"
        %h4.md-subhead
          = "Fat: --------------- #{@aliment.proximate.fat} g"
        %h4.md-subhead
          = "Fiber: -------------- #{@aliment.proximate.fiber} g"
        %h4.md-subhead
          = "Water: ---------- #{@aliment.proximate.water} g"
        %h4.md-subhead
          = "Energy: -------- #{@aliment.proximate.energy} cal"
    %div.modal-footer

app/views/aliments/index.html.erb
<% @title = "search " %>
<% @subtitle = " for" %>

<header class="gems__header">
  <p class="gems__meter">
    <%= page_entries_info @aliments, :entry_name => 'aliment', :model => 'aliment' %>
  </p>
</header>

<% unless @aliments.blank? %>
  <% @aliments.each do |aliment| %>
    <% unless aliment.blank? %>
      <%= link_to aliment_path(aliment), :class => 'gems__gem' do %>
        <span class="gems__gem__info">
          <h2 class="gems__gem__name">
            <%= aliment.name %>
            <span class="gems__gem__version"><%= aliment.id %></span>
          </h2>
          <p class="gems__gem__desc t-text"><%= (aliment.description.blank? || aliment.description.empty?) ? '---' : aliment.description %></p>
        </span>
        <p class="gems__gem__downloads__count">
          <%= aliment.proximate.blank? ? '-' : aliment.proximate.energy.round(2) %>
          <span class="gems__gem__downloads__heading">
            <%= t('rubygems.index.calories') %>
          </span>
        </p>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<%= will_paginate @aliments %>

app/views/aliments/index.html.haml
%div{ id: "breadcrumbs" }
  %a{ href: "http://www.calorieking.com/" } Home
  %a{ href: "http://www.calorieking.com/foods/" } Food Database

%div{ id: "page-content" }
  %div{ id: "search-results-view" }
    %div{ id: "search-results-content" }
      %h2
        Calories in
        %span{ class: "keywords" }
          milk
      %p
        Find nutritional information like calories, carbs, fat, protein and fiber for milk.

      %h3{ class: "food-search-brand-container" }
        %span{ class: "food-search-brand-unlinked" } Average All Brands

      - @aliments.each do |aliment|
        %div{ class: "food-search-result left-vertical-border-green" }
          %span{ class: "food-search-category" }
            = aliment.food_group
          &nbsp:
          = link_to aliment.name, aliments_path(id: aliment), class: "food-search-result-name"

      %h3{ class: "food-search-brand-container" }
        %a{ class: "food-search-brand", href: "http://www.calorieking.com/foods/calories-in-hersheys_b-YmlkPTQ1Mg.html" } Hershey's
        %a{ href: "http://www.calorieking.com/foods/calories-in-hersheys_b-YmlkPTQ1Mg.html", class: "food-search-brand-view-more" } (view more)

      %div{ class: "food-search-result left-vertical-border-blue" }
        %span{ class: "food-search-category" } Chocolate
        &nbsp:
        %a{ class: "food-search-result-name", href: "http://www.calorieking.com/foods/calories-in-chocolate-kisses-milk-chocolate_f-ZmlkPTU4NDcz.html" } Kisses Milk Chocolate
        %span{ class: "food-search-calorie-density" }

      %div{ class: "food-search-result left-vertical-border-blue" }
        %span{ class: "food-search-category" } Chocolate
        &nbsp:
        %a{ class: "food-search-result-name", href: "http://www.calorieking.com/foods/calories-in-chocolate-milk-chocolate-bar_f-ZmlkPTU4NDc1.html" } Milk Chocolate Bar
        %span{ class: "food-search-calorie-density" }

      %h3{ class: "food-search-brand-container" }
        %a{ class: "food-search-brand", href: "http://www.calorieking.com/foods/calories-in-m-ms_b-YmlkPTU5OQ.html" } M&amp;M's
        %a{ href: "http://www.calorieking.com/foods/calories-in-m-ms_b-YmlkPTU5OQ.html", class: "food-search-brand-view-more" } (view more)

      %div{ class: "food-search-result left-vertical-border-blue" }
        %span{ class: "food-search-category" } Chocolate
        &nbsp:
        %a{ class: "food-search-result-name", href: "http://www.calorieking.com/foods/calories-in-chocolate-milk-chocolate-candies_f-ZmlkPTE5MTQx.html" } Milk Chocolate Candies
        %span{ class: "food-search-calorie-density" }

      = paginate @aliments

app/views/aliments/show.js.erb
$('#aliment').html("<%= escape_javascript(render 'show') %>");