config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'pages#index'

  resources :aliments, only: [:index, :show] do
    get :autocomplete_aliment_name, on: :collection

  end

  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'
  post '/' => 'pages#send_contact_email', as: :send_contact_email

end

app/views/pages/about.html.erb
<% @title = t('.title') %>

<div class="l-colspan t-body">
  <p><%= t '.purpose.header', :site => t('title') %></p>
  <ol class="t-numbered-items">
    <li class="t-numbered-item"><%= t '.purpose.all_nutrients' %></li>
    <li class="t-numbered-item"><%= t '.purpose.free' %></li>
    <li class="t-numbered-item"><%= t '.purpose.diet_control' %></li>
  </ol>
  <p>
    <%= t('.founding', founder: link_to('Marcos Serpa', 'https://twitter.com/MarcosSerpa'),
                       :contributors => link_to("291 Rubyists", "https://github.com/rubygems/rubygems.org/graphs/contributors"),
                       :title => t('title')).html_safe %>
  </p>
  <p>
    <%= t('.support', code_polaris: link_to("Code Polaris", "http://codepolaris.com/"),
                      :dockyard => link_to("DockYard", "https://www.dockyard.com/"),
                      :rubygems => link_to("RubyGems", "https://rubygems.org/"),
                      :aws => link_to("AWS", "https://aws.amazon.com")).html_safe %>
  </p>
  <p>
    <%= t('.technical', :rails => link_to("Rails", "http://rubyonrails.org")).html_safe %>
  </p>
</div>

app/views/pages/contact.html.erb
<h1 class="t-display page__heading">
              <a class="t-link--black" href="/contact">Contact</a>

            </h1>
						<div class="form_links sign_up_links t-body">
  <p><a href="/contact">Have some doubt? Want to send us an email?</a></p>
</div>

<%= form_tag send_contact_email_path(anchor: 'contact_us'), class: 'new_user', id: "new_user", novalidate: "", method: :post do %>
	<div class="text_field">
	  <%= label_tag :email, 'email', class: 'form__label' %>
	  <%= email_field_tag :email, '', class: 'form__input' %>
	</div>
	<div class="text_field">
	  <%= label_tag :name, 'name', class: 'form__label' %>
	  <%= text_field_tag :name, '', class: 'form__input' %>
	</div>
	<div class="text_field">
		<%= label_tag :message, 'message', class: 'form__label' %>
	  <%= text_area_tag :message, '', class: 'form__input' %>
	</div>

	<%= submit_tag t('send'), data: { disable_with: t('form_disable_with') }, onclick: "$('#new_user').submit();", class: 'form__submit' %>
<% end %>

app/views/pages/faq.html.erb
<% @title = "FAQ" %>

<div class="t-body">
  <p>
    <%= link_to "This page has been moved onto #{t(:title)}’s new support site.", "http://help.rubygems.org/faqs/gemcutter/faq" %>
  </p>
</div>

app/views/pages/index.html.erb
<div class="home__image-wrap">
  <div class="home__image"></div>
</div>
<h1 class="home__heading"><%= t '.find_your_food' %></h1>

<div class="home__search-wrap">
  <%= form_tag autocomplete_aliment_name_aliments_path, :id => "main-search", :method => :get do %>
    <%= autocomplete_field_tag :name, '', autocomplete_aliment_name_aliments_path, :placeholder => t('layouts.application.header.search_gem').html_safe, autofocus: current_page?(root_url), :id => 'home_query', :class => "home__search" %>
    <%= label_tag :home_query do %>
      <span class="t-hidden"><%= t('layouts.application.header.search_gem').html_safe %></span>
    <% end %>
    <%= submit_tag '⌕', :id => 'search_submit', :name => nil, :class => "home__search__icon" %>
  <% end %>
</div>

<div class="home__cta-wrap">
  <% if @aliments_count %>
    <h2 class="home__downloads">
      <p><%= number_with_delimiter(@aliments_count) %></p>
      <span class="home__downloads__desc"><%= t('home.index.aliments_counting') %></span>
    </h2>
  <% end %>

  <%= link_to t('.app.meet_our_app'), about_path, :class => "home__join #{@aliments_count.nil? ? 'no-download-count' : ''}", "data-icon" => ">" %>
</div>

<div class="home__links">
  <%= link_to t('.footer.status'), "https://status.rubygems.org", class: "home__link", "data-icon" => "⌁" %>
  <%= link_to t('.footer.uptime'), "http://uptime.rubygems.org", class: "home__link", "data-icon" => "⧖" %>
</div>