config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'pages#index'

  resources :aliments, only: [:index, :show] do
    get :autocomplete_aliment_name, on: :collection

  end

  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'
  post '/' => 'pages#send_contact_email', as: :send_contact_email

end

app/views/layouts/_feeds.html.erb
<% if signed_in? %>
  <%= atom_feed_link t(:feed_subscribed), dashboard_url(:api_key => current_user.api_key, :format => :atom) %>
<% end %>

<%= atom_feed_link t(:feed_latest), 'https://feeds.feedburner.com/gemcutter-latest' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-us">
  <head>
    <title><%= page_title %></title>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" name="viewport">
    <meta name="google-site-verification" content="AuesbWQ9MCDMmC1lbDlw25RJzyqWOcDYpuaCjgPxEZY" />
    <link rel="apple-touch-icon" href="/apple-touch-icons/apple-touch-icon.png" />
    <% ["57x57", "72x72", "76x76", "114x114","120x120", "144x144", "152x152", "180x180"].each do |size| %>
      <link rel="apple-touch-icon" sizes="<%= size %>" href="/apple-touch-icons/apple-touch-icon-<%= size %>.png" />
    <% end %>
    <link rel="mask-icon" href="/rubygems_logo.svg" color="#910505">
    <link rel="fluid-icon" href="/fluid-icon.png"/>
    <link rel="search" type="application/opensearchdescription+xml" title="<%=t :title %>" href="/opensearch.xml">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">

    <%= stylesheet_link_tag("application") %>
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
    <link href='https://fonts.googleapis.com/css?family=Roboto:100&amp;subset=greek,latin,cyrillic,latin-ext' rel='stylesheet' type='text/css'>
    <%= render "layouts/feeds" %>
    <%= csrf_meta_tag %>
    <%= yield :head %>
  </head>

  <body class="<%= 'body--index' if request.path_info == '/' %>">
    <header class="header <%= 'header--interior' if request.path_info != '/' %>">
      <div class="l-wrap--header">
        <%= link_to(root_path, title: 'Yummy', class: 'header__logo-wrap') do %>
          <span class="header__logo" data-icon="🍴"></span>
          <span class="t-hidden">Yummy</span>
        <% end %>
        <a class="header__club-sandwich" href="#">
          <span class="t-hidden">Navigation menu</span>
        </a>

        <div class="header__nav-links-wrap">
          <% if request.path_info == "/" %>
            <%= form_tag autocomplete_aliment_name_aliments_path, :id => "main-search", :class => "header__search-wrap--home", :method => :get do %>
              <%= autocomplete_field_tag :name, '', autocomplete_aliment_name_aliments_path, :placeholder => t('.header.search_gem').html_safe, id: 'food-search-input', :class => "header__search" %>
              <%= label_tag :query do %>
                <span class="t-hidden"><%= t('.header.search_gem').html_safe %></span>
              <% end %>
              <%= submit_tag '⌕', :id => 'search_submit', :name => nil, :class => "header__search__icon" %>
            <% end %>
          <% else %>
            <%= form_tag autocomplete_aliment_name_aliments_path, :id => "main-search", :class => "header__search-wrap", :method => :get do %>
              <%= autocomplete_field_tag :name, '', autocomplete_aliment_name_aliments_path, :placeholder => t("layouts.application.header.search_gem").html_safe, id: 'food-search-input', :class => "header__search" %>
              <%= label_tag :query do %>
                <span class="t-hidden"><%= t('.header.search_gem').html_safe %></span>
              <% end %>
              <%= submit_tag '⌕', :id => 'search_submit', :name => nil, :class => "header__search__icon" %>
            <% end %>
          <% end %>

          <nav class="header__nav-links">
            <%- if request.path_info == '/aliments' %>
              <%= link_to "Aliments", aliments_path, class: "header__nav-link is-active" %>
            <%- else %>
              <%= link_to "Aliments", aliments_path, class: "header__nav-link" %>
            <%- end %>

            <%- if request.path_info == '/about' %>
              <%= link_to t('.footer.about'), about_path, class: "header__nav-link is-active" %>
            <%- else %>
              <%= link_to t('.footer.about'), about_path, class: "header__nav-link" %>
            <%- end %>

            <%- if request.path_info == '/contact' %>
              <%= link_to t('.footer.contact'), contact_path, class: "header__nav-link is-active" %>
            <%- else %>
              <%= link_to t('.footer.contact'), contact_path, class: "header__nav-link" %>
            <%- end %>

            <%#- if signed_in? %>
              <!-- <a href="<%#= profile_path(current_user.display_id) %>" class="header__nav-link desktop__header__nav-link"> -->
                <%#= truncate current_user.name %>
                <%#= gravatar 80, "user_gravatar" %>
              <!-- </a>
              <a href="#" class="header__popup-link" data-icon="▼">
                <span class="t-hidden">More items</span>
              </a>
              <div class="header__popup__nav-links"> -->
                <%#= link_to t('.header.dashboard'), dashboard_url, class: "header__nav-link" %>
                <%#= link_to t('.header.sign_out'), log_out_path, method: :delete, class: "header__nav-link" %>
              <!-- </div> -->
            <%#- else %>
              <%#= link_to t('.header.sign_in'), sign_in_path, class: "header__nav-link #{'is-active' if request.path_info == '/sign_in'}" %>
              <%#- if Clearance.configuration.allow_sign_up? %>
                <%#= link_to t('.header.sign_up'), sign_up_path, class: "header__nav-link #{'is-active' if request.path_info == '/sign_up'}" %>
              <%#- end %>
            <%#- end %>
          </nav>
        </div>
      </div>
    </header>

    <% flash.each do |name, msg| %>
      <div id="flash-border" class="flash">
        <div class="flash-wrap">
          <div id="flash_<%= name %>" class="l-wrap--b"><span><%= msg %></span></div>
        </div>
      </div>
    <% end %>

    <%#= render partial: "announcements/public_announcement" %>

    <% if content_for?(:fold) %>
      <div class="fold">
        <%= yield :fold %>
      </div>
    <% end %>

    <main class="<%= 'main--interior' if request.path_info != '/' %>">
      <% if request.path_info != '/' %>
        <div class="l-wrap--b">
          <% if @title %>
            <h1 class="t-display page__heading">
              <%= link_to @title, @title_url, class: "t-link--black" %>

              <% if @subtitle %>
                <i class="page__subheading"><%= @subtitle.html_safe %></i>
              <% end %>
            </h1>
          <% end %>
          <%= yield :title %>
          <%= yield %>
        </div>
      <% else %>
        <%= yield %>
      <% end %>
    </main>

    <footer class="footer">
      <div class="l-wrap--footer">
        <div class="l-overflow">
          <div class="nav--v l-col--r--pad">
            <%- if request.path_info == '/aliments' %>
              <%= link_to t('.footer.aliments'), aliments_path, class: "nav--v__link--footer is-active" %>
            <%- else %>
              <%= link_to t('.footer.aliments'), aliments_path, class: "nav--v__link--footer" %>
            <%- end %>
            <%- if request.path_info == '/about' %>
              <%= link_to t('.footer.about'), about_path, class: "nav--v__link--footer is-active" %>
            <%- else %>
              <%= link_to t('.footer.about'), about_path, class: "nav--v__link--footer" %>
            <%- end %>
            <%- if request.path_info == '/contact' %>
              <%= link_to t('.footer.contact'), contact_path, class: "nav--v__link--footer is-active" %>
            <%- else %>
              <%= link_to t('.footer.contact'), contact_path, class: "nav--v__link--footer" %>
            <%- end %>

            <%- if request.path_info == '/pages/security' %>
              <%#= link_to t('.footer.security'), page_url("security"), class: "nav--v__link--footer is-active" %>
            <%- else %>
              <%#= link_to t('.footer.security'), page_url("security"), class: "nav--v__link--footer" %>
            <%- end %>
          </div>
          <div class="l-colspan--l colspan--l--has-border">
            <div class="footer__about">
              <p>
                <%#= raw t('footer_about',
                  publish_docs: "http://guides.rubygems.org/publishing/",
                  install_docs: "http://guides.rubygems.org/command-reference/#gem-install",
                  api_docs: "http://guides.rubygems.org/rubygems-org-api/",
                  gem_list: rubygems_url,
                  contributing_docs: "http://guides.rubygems.org/contributing/"
                ) %>
              </p>
              <p>
                Yummy is made possible by
                <%= link_to "Marcos Serpa", "http://marcosserpa.me" %>,
                that dedicated time to improve his own health,
                searching for a more complete nutrition tracking,
                using aliments nutrition data publicly available by
                <%= link_to "USDA", "https://www.usda.gov/" %>,
                the U.S. Department of Agriculture.
                No changes on USDA served data was made and USDA has
                none responsibilities of it's use on Yummy.
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class="footer__sponsors-wrap">
        <div class="footer__sponsors">
          <a class="footer__sponsor" href="https://newrelic.com/" target="_blank">
            <%= t("layouts.application.footer.optimized_by") %>
            <span class="t-hidden">New Relic</span>
          </a>
          <a class="footer__sponsor" href="http://get.gaug.es/" target="_blank">
            <%= t("layouts.application.footer.tracking_by") %>
            <span class="t-hidden">Gauges</span>
          </a>
          <a class="footer__sponsor" href="https://www.runscope.com/" target="_blank">
            <%= t("layouts.application.footer.monitored_by") %>
            <span class="t-hidden">Runscope</span>
          </a>
          <a class="footer__sponsor" href="https://travis-ci.org/" target="_blank">
            <%= t("layouts.application.footer.tested_by") %>
            <span class="t-hidden">Travis CI</span>
          </a>

        </div>
      </div>
      <div class="footer__language_selector">
        <% I18n.available_locales.each do |language| %>
          <div class="footer__language">
            <%= link_to I18n.t(:locale_name, locale: language), url_for(locale: language), class: "nav--v__link--footer" %>
          </div>
        <% end %>
      </div>
    </footer>

    <%= javascript_include_tag "application" %>
    <%= yield :javascript %>
    <script type="text/javascript" async defer id="gauges-tracker" data-site-id="4eab0ac8613f5d1583000005" src="//secure.gaug.es/track.js"></script>
  </body>
</html>